import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import { Header } from "@/components/header";
import SmoothScroll from "@/components/SmoothScroll";

const sfPro = localFont({
  src: "../fonts/SF-Pro.ttf",
  display: "swap",
  variable: "--font-sf-pro",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://noahpham.me'),
  title: "Noah Pham - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sfPro.className}>
        <Header />
        <SmoothScroll>
          <main className="pt-20 lg:pt-24">
            {children}
          </main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
